# Generated by Django 3.2.6 on 2021-08-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usermodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
