# Generated by Django 3.2.6 on 2021-08-06 20:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Pic',
            field=models.FileField(null=True, upload_to=app.models.update_filename),
        ),
    ]
